//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinhThiTuyetChinh_Exercise1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEM
    {
        public string MASV { get; set; }
        public string MAMH { get; set; }
        public Nullable<double> DIEM1 { get; set; }
    
        public virtual MONHOC MONHOC { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
